### ISSUE TITLE
Question about categories_id

### ISSUE THREAD

**Issue by Taeyoung96** [immersive-limit/coco-manager#5]
Hi, I'm really thankful for your great code!  
I have a question about categories_id.  
When referring to COCO 2017 data, the category id starts from 1.  
 
<img src="https://user-images.githubusercontent.com/41863759/102955565-8ef74200-4519-11eb-9562-93792a915f0f.png" width="200" height="200">

So, When you make variable `new_id` in `_filter_categories` function,
I think It should start at 1.  

In `filter.py` line 66, `new_id = 1` is more appropriate.  

Do you have any opinions?
Thanks.

**Comment by akTwelve** [comment]
That’s a good point. Yes it probably should start at 1.

**Comment by Taeyoung96** [comment]
@akTwelve If you don't mind, Could I make a Pull Request on these issues?
